find_package(OpenSSL 1.1.1 REQUIRED)
add_library(sa_content STATIC Bundle.cpp)
target_include_directories(sa_content PUBLIC "${CMAKE_CURRENT_LIST_DIR}/include")
target_link_libraries(sa_content PUBLIC sa_data PRIVATE OpenSSL::Crypto)
target_compile_features(sa_content PUBLIC cxx_std_17)
if(MSVC)
    target_compile_options(sa_content PUBLIC /utf-8)
endif()
if(COMMAND sa_apply_warnings)
    sa_apply_warnings(sa_content)
endif()
